name: CI Docker Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Service Docker di dalam GitHub Actions
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.7"

    - name: Install Dependencies
      run: |
        pip install mlflow pandas numpy scikit-learn dagshub protobuf

    - name: Training Model (Generate Run ID)
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

        MLFLOW_TRACKING_URI: "https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Alfarrel.mlflow"
      run: |
        cd MLProject
        python modelling.py

    - name: Login ke Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Download MLflow Model
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_URI: "https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Alfarrel.mlflow"
      run: |
        RUN_ID=$(cat MLProject/run_id.txt)
        echo "Downloading model for run $RUN_ID"
        mlflow artifacts download \
          -r "$RUN_ID" \
          -a models/model \
          -d model_dir


    - name: Build & Push Docker Image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/eksperimen_sml:latest"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
